<?php

$trains = [
    [
        'id' => 1,
        'company' => 'Trenitalia',
        'departure_station' => 'Torino Porta Nuova',
        'arrival_station' => 'Lecce',
        'departure_time' => '10:05:00',
        'arrival_time' => '21:30:00',
        'train_code' => 'FR 1001',
        'num_carriages' => 9,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 2,
        'company' => 'Trenitalia',
        'departure_station' => 'Bologna Centrale',
        'arrival_station' => 'Bari Centrale',
        'departure_time' => '07:55:00',
        'arrival_time' => '16:40:00',
        'train_code' => 'IC 909',
        'num_carriages' => 7,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 3,
        'company' => 'Ferrovie dello Stato',
        'departure_station' => 'Torino Porta Nuova',
        'arrival_station' => 'Roma Termini',
        'departure_time' => '07:45:00',
        'arrival_time' => '13:30:00',
        'train_code' => 'FR 9580',
        'num_carriages' => 10,
        'on_time' => 0,
        'cancelled' => 1,
    ],
    [
        'id' => 4,
        'company' => 'Trenord',
        'departure_station' => 'Milano Cadorna',
        'arrival_station' => 'Como S. Giovanni',
        'departure_time' => '09:20:00',
        'arrival_time' => '10:15:00',
        'train_code' => 'TN 22565',
        'num_carriages' => 6,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 5,
        'company' => 'Italo',
        'departure_station' => 'Roma Tiburtina',
        'arrival_station' => 'Napoli Afragola',
        'departure_time' => '11:00:00',
        'arrival_time' => '13:30:00',
        'train_code' => 'IT 318',
        'num_carriages' => 8,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 6,
        'company' => 'Frecciargento',
        'departure_station' => 'Firenze Rifredi',
        'arrival_station' => 'Bari Centrale',
        'departure_time' => '13:45:00',
        'arrival_time' => '19:20:00',
        'train_code' => 'AV 9985',
        'num_carriages' => 12,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 7,
        'company' => 'Trenitalia',
        'departure_station' => 'Palermo Centrale',
        'arrival_station' => 'Catania Centrale',
        'departure_time' => '08:30:00',
        'arrival_time' => '11:45:00',
        'train_code' => 'REG 6357',
        'num_carriages' => 9,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 8,
        'company' => 'Ferrovie dello Stato',
        'departure_station' => 'Genova Piazza Principe',
        'arrival_station' => 'Torino Porta Susa',
        'departure_time' => '10:15:00',
        'arrival_time' => '11:30:00',
        'train_code' => 'REG 3007',
        'num_carriages' => 7,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 9,
        'company' => 'Trenord',
        'departure_station' => 'Bergamo',
        'arrival_station' => 'Milano Garibaldi',
        'departure_time' => '08:45:00',
        'arrival_time' => '09:30:00',
        'train_code' => 'TN 94260',
        'num_carriages' => 5,
        'on_time' => 1,
        'cancelled' => 0,
    ],
    [
        'id' => 10,
        'company' => 'Italo',
        'departure_station' => 'Venezia Mestre',
        'arrival_station' => 'Roma Termini',
        'departure_time' => '12:30:00',
        'arrival_time' => '16:45:00',
        'train_code' => 'IT 252',
        'num_carriages' => 10,
        'on_time' => 0,
        'cancelled' => 0,
    ],
];

?>
